const express = require('express');
const  {createAccount,getAccount, getAllAccounts, updateAccount, deleteAccount} = require('../controllers/bankAccount.js');
const auth = require('../middleware/auth.js');
const router = express.Router();
router.post('/', auth, createAccount);
router.get('/',auth,getAccount);
router.get('/allAccounts', getAllAccounts);
router.put('/',updateAccount);
router.delete('/', deleteAccount);
module.exports = router;