 const express = require('express');
const router = express.Router();
const auth = require('../middleware/auth.js');
const { createTransaction, getTransactions, getTransaction, deleteTransaction, updateTransaction, deposit, withdrawal} = require('../controllers/transactions.js');
router.post('/',auth, createTransaction);
router.get('/', auth,getTransactions);
router.get('/:id',auth, getTransaction);
router.delete('/:id',auth, deleteTransaction);
router.put('/:id',auth, updateTransaction);
router.post('/deposit',auth, deposit);
router.post('/withdrawal',auth, withdrawal);
module.exports = router;